# Generated by Django 4.1.6 on 2023-02-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample1app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
